version: "3.9"
services:

  # DRS CS
  drs-compliance-suite:
    image: ga4gh/drs-compliance-suite:1.0.3
    command: >
      --server_base_url "<TODO>"
      --platform_name "<TODO>"
      --platform_description "<TODO>"
      --report_path "./output/drs-cs-report.json"
      --drs_version "1.2.0"
      --config_file "config/config_drs.json"
      --serve
      --serve_port 57568
    ports:
      - "57568:57568"
    volumes:
      - "${PWD}/output/:/usr/src/app/output/"
      - "${PWD}/config:/usr/src/app/config"
