version: "3.9"
services:

  # DRS CS
  drs-compliance-suite:
    image: ga4gh/drs-compliance-suite:1.0.2
    command: >
      --server_base_url "http://host.docker.internal:5000/ga4gh/drs/v1"
      --platform_name "ga4gh starter kit drs"
      --platform_description "GA4GH reference implementation of DRS specification"
      --report_path "./output/drs-cs-report.json"
      --drs_version "1.2.0"
      --config_file "config/config_starter_kit_drs.json"
      --serve
      --serve_port 57568
    ports:
      - "57568:57568"
    volumes:
      - "${PWD}/output/:/usr/src/app/output/"
      - "${PWD}/config:/usr/src/app/config"